FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/Gateway.Blazor/Gateway.Blazor.csproj", "src/Gateway.Blazor/"]
RUN dotnet restore "src/Gateway.Blazor/Gateway.Blazor.csproj"
COPY . .
WORKDIR "/src/src/Gateway.Blazor"
RUN dotnet build "Gateway.Blazor.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Gateway.Blazor.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gateway.Blazor.dll"]

